#!/bin/sh
# Copyright (c) 2009, Raymond R. Medeiros. All rights reserved. 

DT_HISTFILE=~/.detroit_history
touch $DT_HISTFILE
if [ -f detroit.jar ]
then
	if [ -x /usr/bin/rlwrap ] 
	then
		rlwrap -f $DT_HISTFILE -H $DT_HISTFILE -n -c -r java -jar detroit.jar "$@"
	else
		java -jar detroit.jar "$@"
	fi
else
	echo "Attempting to build..."
	ant
	if [ -f detroit.jar ]
	then
		./detroit "$@"
	else
		echo "Failed to build: You must have a working JDK and Ant installed!"
	fi
fi
